name: Echo

on:
  push:
    branches:
      - api

jobs:
  echo:
    name: Echo Job
    runs-on: ubuntu-latest

    steps:
      - name: "Say Hello"
        run: echo "Hello, World! This is a dummy API workflow."

  release:
    needs:
      - echo
    uses: ./.github/workflows/release.yml
