name: Release

on:
  workflow_call:
  workflow_dispatch: {}

jobs:
  release:
    name: Semantic Release
    if: ${{ github.event.workflow_run.head_branch == 'api' || github.ref == 'refs/heads/api' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Ensure we are on the 'api' branch. Why this is needed
          # is because the workflow_run event does not provide the branch name.
          ref: api

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

  call-release:
    uses: ./.github/workflows/release.yml # ← works only if release.yml has `workflow_call`
